---
abstract: 'A client for Google APIs Discovery Service'
author:
  - 'Takatsugu Shigeta <shigeta@cpan.org>'
build_requires:
  Test::TCP: 0
configure_requires:
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Google-API-Client
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  HTTP::Request: 0
  JSON: 0
  URI: 0
  URI::Escape: 0
resources:
  bugtracker: https://github.com/comewalk/google-api-perl-client/issues
  homepage: https://github.com/comewalk/google-api-perl-client
  repository: https://github.com/comewalk/google-api-perl-client.git
version: 0.11
x_contributors:
  - 'Gustavo Chaves <gustavo@gnustavo.com>'
  - 'Takatsugu Shigeta <tshigeta@user200.sixapart.jp>'
  - 'Yusuke Ueno <uechoco@gmail.com>'
  - 'shigeta <shigeta@typhoon.(none)>'
